import { NextRequest } from 'next/server';
import { getAssessments, createAssessment, saveQuestions } from '@/lib/assessments';
import { errorResponse, handleApiError, successResponse } from '@/lib/apiResponse';
import { getCurrentProfile, requireRole } from '@/lib/auth/session';
import { authorScopeFor } from '@/lib/auth/access';
import { z } from 'zod';

export async function GET(request: NextRequest) {
  const denied = await requireRole(request, ['admin', 'super_admin', 'staff']);
  if (denied) return denied;
  try {
    const profile = await getCurrentProfile(request);
    if (!profile) return errorResponse('Unauthorized', 401);
    // Teachers see only the papers they wrote; admins see everything.
    const assessments = await getAssessments(authorScopeFor(profile));
    return successResponse({ data: assessments });
  } catch (error) {
    console.error('Error fetching assessments:', error);
    return errorResponse('Failed to fetch assessments', 500);
  }
}

// Targeting replaces the old targetType/targetValue pair. Each entry narrows
// the audience; an empty array means every student may sit it.
const TargetSchema = z
  .object({
    schoolId: z.string().uuid().nullable().optional(),
    level: z.number().int().min(1).max(7).nullable().optional(),
    classId: z.string().uuid().nullable().optional(),
  })
  .transform((t) => ({
    schoolId: t.schoolId ?? null,
    level: t.level ?? null,
    classId: t.classId ?? null,
  }))
  .refine((t) => t.schoolId !== null || t.level !== null || t.classId !== null, {
    message: 'A target must narrow by school, grade level or class',
  });

const QuestionSchema = z.object({
  questionText: z.string().min(1),
  questionType: z.enum([
    'mcq', 'checkbox', 'true_false', 'fill', 'matching', 'dragdrop', 'short', 'long',
  ]),
  options: z.array(z.string()).default([]),
  correctAnswer: z.string().optional(),
  maxScore: z.number().positive().default(1),
  config: z.unknown().optional(),
});

// The ASS#### id is generated by the database, never client-supplied.
const CreateSchema = z.object({
  title: z.string().min(1),
  description: z.string().optional(),
  timeLimit: z.number().min(1),
  opensAt: z.string().optional(),
  closesAt: z.string().optional(),
  status: z.enum(['draft', 'published', 'closed']).optional(),
  targets: z.array(TargetSchema).optional(),
  questions: z.array(QuestionSchema).optional(),
});

export async function POST(request: NextRequest) {
  const denied = await requireRole(request, ['admin', 'super_admin', 'staff']);
  if (denied) return denied;
  try {
    const body = await request.json();
    const validated = CreateSchema.parse(body);
    const profile = await getCurrentProfile(request);

    const assessment = await createAssessment({
      title: validated.title,
      description: validated.description,
      timeLimit: validated.timeLimit,
      opensAt: validated.opensAt,
      closesAt: validated.closesAt,
      status: validated.status,
      targets: validated.targets,
      createdBy: profile?.id,
    });

    if (validated.questions?.length) {
      // Position and code come from array order, so they can never be
      // mistyped, duplicated or raced by the client.
      await saveQuestions(
        assessment.id,
        validated.questions.map((q, i) => ({
          position: i + 1,
          code: `Q${i + 1}`,
          questionText: q.questionText,
          questionType: q.questionType,
          options: q.options,
          correctAnswer: q.correctAnswer,
          maxScore: q.maxScore,
          config: q.config,
        }))
      );
    }

    return successResponse({
      message: 'Assessment created',
      data: { id: assessment.systemId },
    });
  } catch (error) {
    console.error('Error creating assessment:', error);
    return handleApiError(error, 'Creation failed');
  }
}
